### ISSUE TITLE
Skip the `- changes:` layer in `changelog_entry.yaml`

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/yaml-changelog#9]
So `changelog_entry.yaml` just looks like:
```yaml
bump: patch
added:
- Feature
fixed:
- Bug
```
